version: '3.9'

services:
  bot:
    build: .
    container_name: my-bot
    env_file: .env
    network_mode: host # контейнер видит хостовый localhost:5432
    restart: unless-stopped # автозапуск после перезагрузки ВМ
    # ports:                      # при host-сети публикация портов НЕ нужна (игнорируется)
    #   - "3000:3000"
    # опционально: контроль готовности приложения
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://127.0.0.1:${PORT:-3000}/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 5
